// export 'package:flutter/material.dart';
// import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:uber/bloc/page_bloc/verify_code/verify_code_bloc.dart';
// import 'package:uber/bloc/page_bloc/verify_code/verify_code_event.dart';
// import 'package:uber/bloc/page_bloc/verify_code/verify_code_state.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:firebase_storage/firebase_storage.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:get_it/get_it.dart';
// import 'package:uber/scripts/const.dart';
// import 'package:uber/bloc/page_bloc/home_page/home_event.dart';
// //import 'package:uber/widgets/drawer_widget.dart';
// import 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_bloc.dart';
// //import 'package:uber/widgets/avatar_widget_for_view.dart';
// //import 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_bloc.dart';
// //import 'package:uber/widgets/place_for_card_widget.dart';
// //import 'package:uber/widgets/car_image_widget.dart';
// import 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_bloc.dart';
// import 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_event.dart';
// import 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_state.dart';
// //import 'package:uber/widgets/editable_round_avatar_widget.dart';
// import 'package:uber/bloc/widget_bloc/editable_avatar/editable_round_avatar_bloc.dart';
// import 'package:uber/bloc/page_bloc/route_creation/route_creation_bloc.dart';
// //import 'package:uber/widgets/list_of_location_widget.dart';
// //import 'package:uber/widgets/calendar_widget.dart';
// import 'package:uber/bloc/widget_bloc/calendar_widget/calendar_bloc.dart';
// //import 'package:uber/widgets/location_text_field_widget.dart';
// //import 'package:uber/widgets/orange_button.dart';
// import 'package:fluttertoast/fluttertoast.dart';
// import 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_bloc.dart';
// import 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_event.dart';
// import 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_state.dart';
// import 'package:image_picker/image_picker.dart';
// import 'package:flutter/services.dart';
// import 'package:csv/csv.dart';
// import 'package:uber/scripts/text.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'dart:io';
// //import 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_state.dart';
// import 'package:pin_code_fields/pin_code_fields.dart';
// import 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_event.dart';
// import 'package:freezed_annotation/freezed_annotation.dart';

// part 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_bloc.dart';
// part 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_event.dart';
// part 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_state.dart';
// part 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_bloc.freezed.dart';

// part 'package:uber/bloc/page_bloc/home_page/home_bloc.dart';
// part 'package:uber/bloc/page_bloc/home_page/home_state.dart';

// part 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_bloc.dart';
// part 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_state.dart';
// part 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_event.dart';

// part 'package:uber/bloc/page_bloc/route_creation/route_creation_bloc.dart';
// part 'package:uber/bloc/page_bloc/route_creation/route_creation_event.dart';
// part 'package:uber/bloc/page_bloc/route_creation/route_creation_state.dart';
// part 'package:uber/bloc/page_bloc/route_creation/route_creation_bloc.freezed.dart';

// part 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_bloc.dart';
// part 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_event.dart';
// part 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_state.dart';

// part 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_bloc.dart';
// part 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_state.dart';

// part 'package:uber/domain/auth.dart';

// part 'package:uber/extension/bloc_widget_extension.dart';

// part 'package:uber/pages/code_page.dart';
// part 'package:uber/pages/edit_user_information_page.dart';
// part 'package:uber/pages/home_page.dart';
// part 'package:uber/pages/login_or_register_page.dart';
// part 'package:uber/pages/register_user_information_page.dart';
// part 'package:uber/pages/route_creation_page.dart';
// part 'package:uber/pages/sign_in_with_phone_number.dart';

// part 'package:uber/scripts/date_util.dart';
// part 'package:uber/scripts/field_validation.dart';
// part 'package:uber/scripts/image.dart';
// part 'package:uber/scripts/input.dart';
// part 'package:uber/scripts/location.dart';
// part 'package:uber/scripts/routes.dart';
// part 'package:uber/scripts/user_data.dart';
// part 'package:uber/scripts/widgets.dart';

// part 'package:uber/service/navigation_service.dart';
// part 'package:uber/service/toast_service.dart';

// part 'package:uber/style/colors.dart';

// part 'package:uber/widgets/app_large_text.dart';
// part 'package:uber/widgets/app_text.dart';
// part 'package:uber/widgets/avatar_widget_for_view.dart';
// part 'package:uber/widgets/button_widget.dart';
// part 'package:uber/widgets/calendar_widget.dart';
// part 'package:uber/widgets/car_image_widget.dart';
// part 'package:uber/widgets/drawer_widget.dart';
// part 'package:uber/widgets/editable_rectangular_avatar_widget.dart';
// part 'package:uber/widgets/editable_round_avatar_widget.dart';
// part 'package:uber/widgets/icon_and_text_for_drawer_button.dart';
// part 'package:uber/widgets/list_of_location_widget.dart';
// part 'package:uber/widgets/location_text_field_widget.dart';
// part 'package:uber/widgets/long_save_button_widget.dart';
// part 'package:uber/widgets/orange_button.dart';
// part 'package:uber/widgets/place_for_card_widget.dart';
// part 'package:uber/widgets/text_field_for_code_widget.dart';
// part 'package:uber/widgets/text_field_widget.dart';
// part 'package:uber/widgets/toast_widget.dart';
// //part 'package:uber/widgets/app_large_text.dart';

// part 'package:uber/main.dart';

// //part of 'package:uber/scripts/index.dart';
export 'package:flutter/material.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:uber/bloc/page_bloc/verify_code/verify_code_bloc.dart';
export 'package:uber/bloc/page_bloc/verify_code/verify_code_event.dart';
export 'package:uber/bloc/page_bloc/verify_code/verify_code_state.dart';
export 'package:uber/style/colors.dart';
export 'package:uber/widgets/app_large_text.dart';
export 'package:uber/widgets/button_widget.dart';
export 'package:uber/widgets/text_field_for_code_widget.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:firebase_storage/firebase_storage.dart';
export 'package:get_it/get_it.dart';
export 'package:uber/scripts/const.dart';
export 'package:uber/scripts/user_data.dart';
export 'package:uber/service/navigation_service.dart';
export 'package:uber/service/toast_service.dart';
export 'package:uber/extension/bloc_widget_extension.dart';
export 'package:uber/widgets/app_text.dart';
export 'package:uber/widgets/editable_rectangular_avatar_widget.dart';
export 'package:uber/widgets/long_save_button_widget.dart';
export 'package:uber/widgets/text_field_widget.dart';
export 'package:uber/bloc/page_bloc/home_page/home_event.dart';
export 'package:uber/widgets/avatar_widget_for_view.dart';
export 'package:uber/widgets/drawer_widget.dart';
export 'package:uber/widgets/place_for_card_widget.dart';
export 'package:uber/widgets/car_image_widget.dart';
export 'package:uber/bloc/widget_bloc/editable_avatar/editable_round_avatar_bloc.dart';
export 'package:uber/widgets/editable_round_avatar_widget.dart';
export 'package:uber/bloc/widget_bloc/calendar_widget/calendar_bloc.dart';
export 'package:uber/widgets/calendar_widget.dart';
export 'package:uber/widgets/list_of_location_widget.dart';
export 'package:uber/widgets/location_text_field_widget.dart';
export 'package:uber/widgets/orange_button.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_bloc.dart';
export 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_event.dart';
export 'dart:core';
export 'package:image_picker/image_picker.dart';
export 'package:flutter/services.dart';
export 'package:csv/csv.dart';
export 'package:uber/pages/edit_user_information_page.dart';
export 'package:uber/pages/home_page.dart';
export 'package:uber/pages/login_or_register_page.dart';
export 'package:uber/pages/route_creation_page.dart';
export 'package:uber/pages/sign_in_with_phone_number.dart';
export 'dart:io';
export 'package:uber/domain/auth.dart';
export 'package:uber/scripts/text.dart';
export 'package:uber/widgets/toast_widget.dart';
export 'package:uber/pages/code_page.dart';
export 'package:uber/pages/register_user_information_page.dart';
export 'package:uber/scripts/widgets.dart';
export 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_event.dart';
export 'package:uber/scripts/date_util.dart';
export 'package:uber/widgets/icon_and_text_for_drawer_button.dart';
export 'package:uber/scripts/image.dart';
export 'package:uber/bloc/widget_bloc/editable_avatar/editable_round_avatar_event.dart';
export 'package:uber/bloc/widget_bloc/editable_avatar/editable_round_avatar_state.dart';
export 'package:uber/scripts/input.dart';
export 'package:pin_code_fields/pin_code_fields.dart';
export 'package:firebase_core/firebase_core.dart';

//export 'package:uber/bloc/widget_bloc/editable_rectangular_avatar/editable_rectangular_avatar_bloc.dart';
//export 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_event.dart';
//export 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_state.dart';
//export 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_bloc.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:uber/bloc/page_bloc/home_page/home_state.dart';
export 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_event.dart';
export 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_state.dart';
export 'package:uber/scripts/field_validation.dart';
export 'package:uber/scripts/location.dart';
//export 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_state.dart';
export 'package:uber/bloc/page_bloc/sign_in_with_phone_page/sign_in_with_phone_state.dart';
export 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_event.dart';
export 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_state.dart';
export 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_state.dart';
export 'package:uber/bloc/page_bloc/edit_user_information/edit_user_information_bloc.dart';
//export 'package:uber/bloc/widget_bloc/editable_rectangular_avatar/editable_rectangular_avatar_bloc.dart';
export 'package:uber/bloc/widget_bloc/view_avatar/view_avatar_bloc.dart';
export 'package:uber/bloc/widget_bloc/drawer_widget/drawer_widget_bloc.dart';

export 'package:uber/bloc/widget_bloc/editable_rectangular_avatar/editable_rectangular_avatar_bloc.dart';
export 'package:uber/bloc/page_bloc/home_page/home_bloc.dart';
export 'package:uber/bloc/page_bloc/register_user_information_page/register_user_information_bloc.dart';
export 'package:uber/bloc/page_bloc/route_creation/route_creation_bloc.dart';
export 'package:uber/scripts/routes.dart';
